# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05d23f5ef54bb73be84783b11cc5c6fc8dd1ee9ef66f1ea46f1c5211f7ce7071eb55bea1ae16f6393f15e6d5cc29087428e81041bb44408a5a7f6fa6995c8362

test:
  secret_key_base: 9f7afd1b836778cc1e4d1982363dc1f5774515da423820cf6849259618590c4460a8bd447c201cd1a8e33a38a2438de84e0ef3992999cb0448f78a924a950325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
